#Creating numpy array.

In [72]:
#grime time
import numpy as np

In [73]:
list1 = [2, 4, 6, 8, 10]
array_np1 = np.array(list1)

In [74]:
list1

[2, 4, 6, 8, 10]

In [75]:
array_np1

array([ 2,  4,  6,  8, 10])

In [76]:
type(array_np1)

numpy.ndarray

In [77]:
array_np1 + 1


array([ 3,  5,  7,  9, 11])

In [78]:
#converting int array to float array
list_2d = [(1, 2, 3),
          (4, 5, 6),
          (7, 8, 9)]
array_2d = np.array(list_2d, dtype = 'float')

In [79]:
array_2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [80]:
array_2d_int = array_2d.astype('int')

In [81]:
array_2d_int

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
array_2d_bool =np.array(list_2d, dtype = 'bool')
array_2d_bool

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [83]:
array_all = np.array([1, 2, 3, 5, False, 'Grime Time'], dtype = 'object')
array_all

array([1, 2, 3, 5, False, 'Grime Time'], dtype=object)

In [84]:
#converting array to list
list2 = array_all.tolist()

In [85]:
list2

[1, 2, 3, 5, False, 'Grime Time']

In [86]:
#SUMMARY:
#converting list to np array: array1 = np.array(list1)
#converting list to another np array type: array1 = np.array(list1, dtype = 'float')
#converting array back to int: array2 = array1.astype('int')
#converting array back to list: list2 = array2.tolist()

#float/bool/objcet(all types are allowed)

#array dimensions

In [87]:
array_2d.shape

(3, 3)

In [88]:
array_2d.size

9

In [89]:
array_2d.dtype

dtype('float64')

In [90]:
array_2d.ndim

2

In [91]:
#SUMMARY:
#shape of the array: array1.shape
#size of the array: array1.size
#type of the array: array1.dtype
#dimension of the array: array1.ndim

#Reversing rows and columns

In [92]:
array_2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [93]:
array_2d[::-1]
#reversing the rows

array([[7., 8., 9.],
       [4., 5., 6.],
       [1., 2., 3.]])

In [94]:
array_2d[::-1, ::-1]
#reversing the columns

array([[9., 8., 7.],
       [6., 5., 4.],
       [3., 2., 1.]])

In [95]:
#SUMMARY:
#reversing the rows: array1[::-1]
#reversing the columns: array1[::-1, ::-1]

#Specific Element Extraction

In [96]:
#first row and all columns
array_2d[0, :]

array([1., 2., 3.])

In [97]:
array_2d[:2, :]
#all rows till 2 and all columns

array([[1., 2., 3.],
       [4., 5., 6.]])

In [98]:
array_2d[:-1, :]
#all rows except from last one and all columns

array([[1., 2., 3.],
       [4., 5., 6.]])

In [99]:
array_2d[:, 1:3]
#all rows and columns from 1 to 3

array([[2., 3.],
       [5., 6.],
       [8., 9.]])

In [100]:
#SUMMARY:
#all rows or column: [:, :]
#all rows til the last one and all columns: [:-1, :]
#all rows till the 5 and all column: [:5, :]
#all rows from 5 to 10 and all columns: [1:5, :]

#Basic Statistics

In [101]:
array_2d.min()
#min value search

1.0

In [102]:
array_2d.max()
#max value search

9.0

In [103]:
array_2d.sum()
#sum of all elements

45.0

In [104]:
array_2d.mean()
#mean element search

5.0

In [105]:
np.average(array_2d)
#mean element search

5.0

In [106]:
np.median(array_2d)
#median element search

5.0

In [107]:
np.var(array_2d)
#variance of the all elements

6.666666666666667

In [108]:
#SUMMARY: 
#min value: array1.min()
#max value: array1.max()
#sum of the values: array1.sum()
#mean of the array: array1.mean() or np.average(array1)
#median of the array: np.median(array1)
#variance of the array: np.var(array1)


#Reshaping and flattering

In [109]:
array_2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [110]:
array_2d.reshape(1, 9)
#reshaping array; size should be the same

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [111]:
flat1 = array_2d.flatten()
flat1
#removing all dimensions and flattering

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [112]:
#SUMMARY:
#reshaping array: array1.reshape(x, y) // if: x * y == array1.size()
#flattering array: array1.flatten()

#Creating Random Arrays and Sequences

In [113]:
np.arange(10)
#creating array starting from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.arange(2, 10)
#creating array starting from 2 to 9

array([2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
np.arange(0, 10, 2)
#creating array starting from 0 and only after each 2 elements(in this case it's only even numbers)

array([0, 2, 4, 6, 8])

In [116]:
np.arange(10, 0, -1)
#creating array in descending sequence starting from 10 and till 0, decreasing by 1 each row

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [117]:
np.linspace(0, 10, 3)
#creating array where it automatically calculate equal step size from x to y.

array([ 0.,  5., 10.])

In [118]:
np.zeros([2, 2])
#creating given dimensional array with all elements equal to zero

array([[0., 0.],
       [0., 0.]])

In [119]:
#SUMMARY:
#array from x to y: mp.arange(x, y)
#array from x to y, each step after z: np.arange(x, y, z)
#array from x to y, x > y, after 1: np.arange(x, y, -1)
#array that breakes range into equal placed numbers: np.linspace(x, y, z) // z is the array size
#array that consists of zeros with any dimension: np.zeros([x, y]) // x - rows, y - culomns

#Unique Items and Count

In [120]:
array3 = [[1, 2, 3, 4, 5],
          [6, 7, 8, 9, 10]]

In [121]:
u_val, count = np.unique(array3, return_counts = True)

In [122]:
u_val

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
count

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [124]:
#SUMMARY:
#counting unique values: u_val, count = np.unique(array1, return_counts = True)

#Documentation and Help

In [125]:
a = [1, 2, 3, 4, 5]
b = np.array(a, dtype = 'float64')

In [126]:
set(dir(b))- set(dir(object))
#list of all unique methods of np array

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setitem__',
 '__setstate__',
 '__sub__',


In [127]:
np.lookfor('variance')
#searching for functions using key words

Search results for 'variance'
-----------------------------
numpy.cov
    Estimate a covariance matrix, given data and weights.
numpy.var
    Compute the variance along the specified axis.
numpy.nanvar
    Compute the variance along the specified axis, while ignoring NaNs.
numpy.ma.cov
    Estimate the covariance matrix.
numpy.ma.var
    Compute the variance along the specified axis.
numpy.matrix.var
    Returns the variance of the matrix elements, along the given axis.
numpy.chararray.var
    Returns the variance of the array elements, along given axis.
numpy.ma.MaskedArray.var
    Compute the variance along the specified axis.
numpy.std
    Compute the standard deviation along the specified axis.
numpy.nanstd
    Compute the standard deviation along the specified axis, while
numpy.hamming
    Return the Hamming window.
numpy.polyfit
    Least squares polynomial fit.
numpy.corrcoef
    Return Pearson product-moment correlation coefficients.
numpy.ma.anom
    Compute the anomalies (dev

In [128]:
np.ma.mean?
#asking for what exact function does

In [129]:
arr = np.array([[[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]], 
                [[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]]])
print(arr)

[[[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]

 [[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]]


In [130]:
print("len:", len(arr), "-- количество элементов по первой оси.",
      "\nsize:", arr.size, "-- всего элементов в матрице.",
      "\nndim:", arr.ndim, "-- размерность матрицы.",
      "\nshape:", arr.shape, "-- количество элементов по каждой оси.")

len: 2 -- количество элементов по первой оси. 
size: 24 -- всего элементов в матрице. 
ndim: 3 -- размерность матрицы. 
shape: (2, 3, 4) -- количество элементов по каждой оси.


In [132]:
#array that consists of only ones
array1 = np.ones(7, dtype = np.int16)
array1

array([1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [133]:
#creating an array with the same size
array2 = np.zeros_like(array1)
array2

array([0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [136]:
#creating a linspace alike array where first arguement is starting point and power of 10, second arguement is ending point and power of ten, third one is number of elements between them
logarr = np.logspace(0, 3, 12)
logarr
#linspace from 10**0 to 10**3

array([   1.        ,    1.87381742,    3.51119173,    6.57933225,
         12.32846739,   23.101297  ,   43.28761281,   81.11308308,
        151.9911083 ,  284.80358684,  533.66992312, 1000.        ])

#Operations with 1d arrays

In [138]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)

print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

#operations bw two arrays are possible only if sizes are equal

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
[  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
[-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


In [139]:
print(5 * a)
print(15 + b)

[ 15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165.]
[13. 11.  9.  7.  5.  3.  1. -1. -3. -5. -7.]


In [140]:
print((a + b) ** 2)
print(2 ** (a + b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


#UFUNC Functions/ Elementary

In [141]:
#sin, cos, log, etc.
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [142]:
np.log(a)

array([1.09861229, 1.79175947, 2.19722458, 2.48490665, 2.7080502 ,
       2.89037176, 3.04452244, 3.17805383, 3.29583687, 3.40119738,
       3.49650756])

In [144]:
print(a)
print(b)
print(a > b)
print(a == b)
print(a >= 10)
#logical opeartions

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]
[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


In [147]:
#Quantifiers for ALL and for given ANY
c = np.arange(0., 20)
np.any(c == 0.), np.all(c != 0.)

(True, False)

In [151]:
%%time
print(np.e, np.pi)
#const values.

2.718281828459045 3.141592653589793
Wall time: 0 ns


In [154]:
print(c)
print(c.cumsum()) #жиілік қосындысы

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
[  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91.
 105. 120. 136. 153. 171. 190.]


In [155]:
a = np.array([-9, 5, 0, 2, 24, -1, 2, 4])
#sorting without changing
print(np.sort(a))
print(a)

[-9 -1  0  2  2  4  5 24]
[-9  5  0  2 24 -1  2  4]


In [156]:
#sorting with changes
a.sort()
print(a)

[-9 -1  0  2  2  4  5 24]


In [159]:
#combining arrays:
print(a)
b = np.ones(5)
print(b)
print(b * 3)
c = np.hstack((a, b, b * 3))
print(c)

[-9 -1  0  2  2  4  5 24]
[1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3.]
[-9. -1.  0.  2.  2.  4.  5. 24.  1.  1.  1.  1.  1.  3.  3.  3.  3.  3.]


In [160]:
#breaking arrays:
x1, x2, x3, x4 = np.hsplit(a, [3, 5, 6])
print(a)
print(x1)
print(x2)
print(x3)
print(x4)

[-9 -1  0  2  2  4  5 24]
[-9 -1  0]
[2 2]
[4]
[ 5 24]


#Functions: append-delete-insert: not inplace, do not save values.

In [161]:
print(np.delete(a, [2, 4, 1]))
print(a)

[-9  2  4  5 24]
[-9 -1  0  2  2  4  5 24]


In [162]:
np.insert(a, 2, [-1, -1])

array([-9, -1, -1, -1,  0,  2,  2,  4,  5, 24])

In [163]:
np.append(a, [2.2, 2.1])

array([-9. , -1. ,  0. ,  2. ,  2. ,  4. ,  5. , 24. ,  2.2,  2.1])

Working with the indexes

In [165]:
a = np.array([2, 42, 65, 76, 87, 12])
b = a[1:3] #copy is not created: all changes occured in b would change a too.
print(b)

b[0] = -100
print(b)
print(a)

[42 65]
[-100   65]
[   2 -100   65   76   87   12]


In [166]:
#doubling or copying another array
b = a.copy()
b[2] = -100000
print(a)
print(b)

[   2 -100   65   76   87   12]
[      2    -100 -100000      76      87      12]


**Задание 3:**  
- Создать массив чисел от $-4\pi$  до $4\pi $, количество точек 100
- Посчитать сумму поэлементных квадратов синуса и косинуса для данного массива  
- С помощью ``np.all`` проверить, что все элементы равны единице.

In [171]:
%%time
pi = np.pi
a = np.linspace(-4 * pi, 4 * pi, 100)
sin = np.sin(a)
cos = np.cos(a)
sum_sin = (sin.sum())**2
sum_cos = (cos.sum())**2

print('array:', a)
print('square of sin sums:', sum_sin)
print('square of cos sums:', sum_cos)
print('are all elements equal to 1?:', np.all(a == 1))


array: [-12.56637061 -12.31250454 -12.05863847 -11.8047724  -11.55090632
 -11.29704025 -11.04317418 -10.7893081  -10.53544203 -10.28157596
 -10.02770988  -9.77384381  -9.51997774  -9.26611167  -9.01224559
  -8.75837952  -8.50451345  -8.25064737  -7.9967813   -7.74291523
  -7.48904915  -7.23518308  -6.98131701  -6.72745093  -6.47358486
  -6.21971879  -5.96585272  -5.71198664  -5.45812057  -5.2042545
  -4.95038842  -4.69652235  -4.44265628  -4.1887902   -3.93492413
  -3.68105806  -3.42719199  -3.17332591  -2.91945984  -2.66559377
  -2.41172769  -2.15786162  -1.90399555  -1.65012947  -1.3962634
  -1.14239733  -0.88853126  -0.63466518  -0.38079911  -0.12693304
   0.12693304   0.38079911   0.63466518   0.88853126   1.14239733
   1.3962634    1.65012947   1.90399555   2.15786162   2.41172769
   2.66559377   2.91945984   3.17332591   3.42719199   3.68105806
   3.93492413   4.1887902    4.44265628   4.69652235   4.95038842
   5.2042545    5.45812057   5.71198664   5.96585272   6.21971879
   6.

In [173]:
# решение

x = np.linspace(-4*np.pi, 4*np.pi, 100)
np.all((np.sin(x)**2 + np.cos(x)**2).round() == 1)

True

#TWO-D Array

In [176]:
b = np.arange(0, 20)
b.shape = (2, 10)
print(b)
#reformating from 1d to 2d

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [177]:
a = np.ones((3, 3)) # подать tuple
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [178]:
c = np.eye(3)
print(c)
#square matrix with 1 one diagonal.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [179]:
d = np.diag(np.array([1, 2, 3, 4]))
print(d)
#filling diagonal, other cells are equal to 0

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


***Задание 4:***
Создать квадратную матрицу размера 8, на главной диаг. арифметическая прогрессия с шагом 3 (начиная с 3), а на побочной -1, остальные элементы 0.

In [181]:
matrix = -1 * np.eye(8)[::-1] + np.diag(np.arange(3, 27, 3))

print(matrix)

[[ 3.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  6.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  9.  0.  0. -1.  0.  0.]
 [ 0.  0.  0. 12. -1.  0.  0.  0.]
 [ 0.  0.  0. -1. 15.  0.  0.  0.]
 [ 0.  0. -1.  0.  0. 18.  0.  0.]
 [ 0. -1.  0.  0.  0.  0. 21.  0.]
 [-1.  0.  0.  0.  0.  0.  0. 24.]]


#Production of Matrixes

In [183]:
a = 5 * np.ones((5, 5))
b = np.eye(5) + 1

print(a, '\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [185]:
print(a*b, '\n') # поэлементное умножение
print(a @ b, '\n') # матричное умножение
print(a.dot(b)) #method that also can be used for scalar multiplication of two vectors

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


**Двумерные массивы, зависящие только от одного индекса: $x_{ij}=u_j$, $y_{ij}=v_i$**

In [186]:
u = np.linspace(1, 2, 2)
v = np.linspace(4, 8, 3)
print(u)
print(v)

[1. 2.]
[4. 6. 8.]


In [187]:
x, y = np.meshgrid(u, v)
print(x, '\n')
print(y)

[[1. 2.]
 [1. 2.]
 [1. 2.]] 

[[4. 4.]
 [6. 6.]
 [8. 8.]]


***Задание 5:***
- Отобразить вектор размера 100, в котором вычеркивается **x**, если **x** --- составное (т. е. не является простым)

In [188]:
is_prime = np.ones(100, dtype = 'bool')

In [189]:
is_prime[:2] = False

In [190]:
n = int(np.sqrt(len(is_prime)))
for i in range(2, n):
    is_prime[2 * i ::i] = False

print(is_prime)

[False False  True  True False  True False  True False False False  True
 False  True False False False  True False  True False False False  True
 False False False False False  True False  True False False False False
 False  True False False False  True False  True False False False  True
 False False False False False  True False False False False False  True
 False  True False False False False False  True False False False  True
 False  True False False False False False  True False False False  True
 False False False False False  True False False False False False False
 False  True False False]


In [191]:
print(is_prime[17])
print(is_prime[25])

True
False


**Masks** - массив булевских переменных, такого же размера как и исходный массив

In [193]:
a = np.arange(20)
print(a % 3 == 0)
print(a[a % 3  == 0]) #mask returns all values that are true for mask conditional

[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


***След (trace) - сумма диагональных элементов.***

In [194]:
b = np.diag(a[a >= 10])
print(b)
print(np.trace(b))

[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]
145


**Tensors**

In [196]:
x = np.arange(64).reshape(8, 2, 4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [199]:
x.shape, len(x), x.size, x.ndim

((8, 2, 4), 8, 64, 3)

In [200]:
np.sum(x)

2016

In [206]:
print(np.sum(x, axis=0), '\n') #column sum in all tensor and representing 2d matrix form(*, [a, b])
print(np.sum(x, axis=1), '\n') #column sum in submatrixes(2d form) and representing 2d matrix form([a, *, b])
print(np.sum(x, axis=2), '\n') #row sum in submatrixes(2d form) and representing 2d matrix form([a, b], *)

# суммируем сразу по двум осям, то есть для фиксированной i 
# суммируем только элементы с индексами (i, *, *)
print(np.sum(x, axis=(1, 2))) #sum of all columns and rows in 2d submatrixes in 1d form.([a], *, *)

[[224 232 240 248]
 [256 264 272 280]] 

[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]] 

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]] 

[ 28  92 156 220 284 348 412 476]


**Linear Algebra Operations**


In [212]:
#Определитель
a = np.array([[2, 1], [2, 3]])
print(a)

np.linalg.det(a) #2 * 3 - 2 * 1 = 4

[[2 1]
 [2 3]]


4.0

In [216]:
#Обратимая матрица, inverse
b = np.linalg.inv(a)
print(b)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


In [221]:
#когда матрица необратима
c = np.array([[2, 1], [6, 3]], dtype = 'float64')
print(c)
print(np.linalg.det(c))

[[2. 1.]
 [6. 3.]]
0.0


In [220]:
np.linalg.det(c) #обратная матрица необратима

0.0

**Неоднородные линейные уравнения**

In [222]:
# A * x = u
v = np.array([5, -10])
print(np.linalg.solve(a, v))
print(b.dot(v))

[ 6.25 -7.5 ]
[ 6.25 -7.5 ]


***Найдем собственные вектора матрицы A.***
$$ A \cdot x = \lambda \cdot x $$

In [223]:
l, u = np.linalg.eig(a)
print(l)
print(u)

[1. 4.]
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


***Собственные значения матриц A и A.T совпадают.***

In [224]:
l, u = np.linalg.eig(a.T)
print(l)
print(u)

[1. 4.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [225]:
l, u = np.linalg.eig(np.eye(3))
print(l)
print(u)

[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
